target 'iosPennyDrop' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
